<a href="https://colab.research.google.com/github/MatchLab-Imperial/deep-learning-course/blob/master/week08_Deep_Reinforcement_Learning_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Reinforcement Learning: An Introduction 👾

In this tutorial we enter in the world of Deep Reinforcement Learning (DRL). In particular, we will first familiarize ourselves with some basic concepts of Reinforcement Learning (RL), then we will implement a classical tabular Q-learning method for the [Frozen Lake](https://gym.openai.com/envs/FrozenLake-v0/) problem and finally, implement a Deep Q-learning approach for the [CartPole](https://gym.openai.com/envs/CartPole-v1/) problem.


> 



![alt text](https://media2.giphy.com/media/46ib09ZL1SdWuREnj3/giphy.gif?cid=3640f6095c6e92762f3446634d90bc65) ![alt text](https://media0.giphy.com/media/d9QiBcfzg64Io/200w.webp?cid=3640f6095c6e93e92f30655873731752)![alt text](https://i.gifer.com/GpAY.gif)

The gifs above, show the results obtained by [deepmind ](https://arxiv.org/pdf/1312.5602v1.pdf). They successfully trained an RL agent using deep Q-learning  to play classical Atari arcade games. Cool ain't it? Let's see how they did it.





---

---



# Reinforcement Learning 📑:
RL is an area of machine learning that addresses how an agent can learn to behave on an specific environment in order to maximize a predefined goal.  Just like humans learn to walk, this ML field learns by trial and error, as an agent learns by interacting with the environment and getting feedback regarding the performed actions.

![alt text](https://keon.io/images/deep-q-learning/rl.png)

The above picture ([source](https://keon.io/deep-q-learning/)) gathers all the typical steps involved in any RL problem. 

1.   At time $t$ the agent observes the environment state denoted by $S_t$.
2.   Based on this observation, chooses an action $A_t$.
3.  After performing the action $A_t$ gets a reward $R_t$ from the environment.
4. The agent observes a new state $S_{t+1}$.

The goal of the agent is to maximize its cumulative reward, called return. Reinforcement learning methods consist of different approaches so the agent can learn behaviors to maximize its goal.

Following we list the main concepts that you should familiarise yourselfves with:


*   **State Space ($\mathcal{S}$):** Refers to the set of possible states where an agent might find himself while interacting with the environment.  
*   **Action Space ($\mathcal{A}$):** Refers to the set of all valid actions in a given environment. Some environments, like Atari, have discrete action spaces, where only a finite number of moves are available to the agent (left, right, up and down). Other environments, like the control of a robotic arm, have continuous action spaces, where actions are real-valued vectors, e.g., move the robotic arm x= 3.51 cm, y = 1cm and z=0.1cm.
* **Policy ($\pi$):** A policy is a rule used by an agent to decide, given a state, what actions to take.  A policy can be deterministic, i.e., given a particular state the agent will always choose the same action to perform in this state, or stochastic, where for a particular state, an agent will choose from a set of actions with some probability distribution.

*   **Return:**  The goal of the agent is to maximize the overall obtained discounted reward also known as return:

$$G_t=\sum ^{\infty} _{k=0} \gamma ^t R_{t+k+1}$$




> Where $0\leq\gamma\leq 1$ is the discounted factor, and regulates how far into the future the agent is "looking". If $\gamma=0$, the agent is only concerned with the immediate reward, while if $ \gamma=1$ the agent is concerned with the overall experience reward. Why would we ever want a discount factor, though? Don’t we just want to get all rewards? We do, but the discount factor is both intuitively appealing and mathematically convenient. On an intuitive level: cash now is better than cash later. Mathematically: an infinite-horizon sum of rewards may not converge to a finite value and is hard to deal with in equations.


 * **Value functions:** Refers to the value of a state $V(s)$, or state-action pair $Q(s,a)$. By value, we mean the expected return if you start in that state ($S_t=s$) or state-action $(S_t=s,A_t=a)$ pair, and then act according to your policy forever after. Mathematically, we can define state value function and state-action pair as follows:
$ V\left(S\right) \doteq \mathop{\mathbb{E_\pi}} \left[\sum ^{\infty} _{k=0} \gamma ^t R_{t+k+1} \mid S_t=s\right].$ and $Q\left(s,a\right) \doteq \mathop{\mathbb{E_\pi}}\left[\sum ^{\infty} _{k=0} \gamma ^t R_{t+k+1}\mid S_t=s,A_t=a\right]$.




---


# Q-Learning 😍
This family of RL methods try to learn an approximator of the action-value functions $Q(s,a)$  based on the [Bellman equation](https://en.wikipedia.org/wiki/Bellman_equation), such that the update using a classical [gradient descent ](https://en.wikipedia.org/wiki/Gradient_descent) formulation is given by:
$$Q\left(s,a\right)=Q\left(s,a\right)+ \alpha \left(r+\gamma \max _{a} Q\left(s_{t+1},a\right)-Q\left(s,a\right)\right).$$
Where $\alpha$ is the step size. 
 Q-Learning updates the estimated reward at each time step and  uses the old estimate $ \max _{a}Q\left(s_{t+1},a\right)$ to update the new ones. In a more algorithmic way, the Q-Learning process is the following:


1.   Initialize Q-values at random $Q\left(s,a\right)$.
2. Forever or until learning is stopped do:
> 1.  Observe state $s$.
> 2.   Take action $a$ according to your policy, e.g., $\epsilon-greedy$.
> 3.   Observe reward $r$ and new state $s_{t+1}$.
> 4. Based on your actual estimates, compute $\max _{a}Q\left(s_{t+1},a\right)$.
> 5. Update your current estimate for  $Q\left(s,a\right)$:
$$Q\left(s,a\right)=Q\left(s,a\right)+ \alpha \left(r+\gamma \max _{a} Q\left(s_{t+1},a\right)-Q\left(s,a\right)\right).$$

Okay, now that we are familiar with Q-Learning lets jump to a real implementation of it. 🙌








---


# 🕹️ Tabular Q-Learning with Frozen Lake  🕹️
❄️❄️ Brace yourselves, winter is coming! ❄️❄️ In this section we will teach an agent how to play  the [Frozen lake](https://gym.openai.com/envs/FrozenLake-v0/) game using  a classical tabular Q-learning . 
![alt text](https://raw.githubusercontent.com/simoninithomas/Deep_reinforcement_learning_Course/1ee37cfc3130057f828f19b3cee6066d41c1eeb4/Q%20learning/FrozenLake/frozenlake.png)

Winter has arrived and you and your friends were tossing around a frisbee at the park when you made a wild throw that left the frisbee out in the middle of the lake. The water is mostly frozen, but there are a few holes where the ice has melted. If you step into one of those holes, you'll fall into the freezing water. At this time, there's an international frisbee shortage, so it's absolutely imperative that you navigate across the lake and retrieve the disc. However, the ice is slippery, so you won't always move in the direction you intend.
The goal of this game is to go from the starting state (S) to the goal state (G) by walking only on frozen tiles (F) and avoid holes (H). However, the ice is slippery (!!), so you won't always move in the direction you intend (stochastic environment), i.e., there is a probability $p$ that you move in the direcction selected and a probability $(1-p)$ that given the slippery ice, you move to a random position near positon. 

The lake is represented by a 4x4 grid and the location where the frisbee has landed (G) as well as the holes (H) is always the same for every new game. The game is restarted every time you have successfully recovered the frisbee or you have fallen into the cold waters. A reward of +1 is given every time you recover the frisbee and 0 other way.


**Step 0: Import the needed libraries:**

We will be using 3 libraries:

* Numpy for our Qtable.
* OpenAI Gym for our FrozenLake Environment
* Random to generate random numbers



In [0]:

from IPython.display import HTML
import numpy as np
import gym
import random

**Environment creation:**

OpenAi is  a library composed of many environments that we can use to train our agents, in our case we choose to use the Frozen Lake.

In [0]:
env = gym.make("FrozenLake-v0")

**Q-table **

 Now, we'll create our Q-table. The goal of the Q-table is to store the estimates $Q\left(s,a\right)$ and retrieve them when necessary. In this game the states are represented by each of the 16 grid positions being 0 the starting position and 16 the goal position and the actions are 4: left, right, up and down. Our Q-table will have then $16 \times 4$ positions, where the value of the first column of the first row represents the expected return of being in position 0 and taking left.
 
The number of rows (states) and columns (actions) the table will have can also be obtained using the values action_size and the state_size from the OpenAI Gym library: *env.action_space.n* and* env.observation_space.n*.
 
We initialize the table to 0.



In [0]:
action_size = env.action_space.n
state_size = env.observation_space.n
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Hyperparameters** ⚙️

Following, we specify the hyperparameters:


In [0]:
total_episodes = 25000        # Total episodes
learning_rate = 0.8           # Learning rate (alpha in the previous formulation)
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

At first, we don't know how to interact with the environment (Q-table values set to 0), so we start exploring it by taking random action with probability $\epsilon=1$, capturing the rewards obtained and updating the Q-values of the table accordingly. As time passes by, we start knowing more and more the environment, so we reduce (decay_rate) the probability of taking a random action and we start exploiting our knowledge, we choose the action that leads us to the highest reward, i.e., the one with the highest Q-value.

In [0]:
# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

**Q-Learning** 🧠

Now we implement the Q learning algorithm: 
> 1.  Observe state $s$.
> 2.   Choose a random value $v$ between 0 and 1.
> 3. If $v<\epsilon$, we choose a random action, otherwise we select the action with maximum $Q(s,a)$.
> 3.   Observe reward $r$ and new state $s_{t+1}$.
> 4. Based on your previous estimates, compute $\max _{a}Q\left(s_{t+1},a\right)$.
> 5. Update your current estimates for  $Q\left(s,a\right)$:
$$Q\left(s,a\right)=Q\left(s,a\right)+ \alpha \left(r+\gamma \max _{a} Q\left(s_{t+1},a\right)-Q\left(s,a\right)\right).$$


In [0]:


# List of rewards
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)



Score over time: 0.48484
[[1.03140688e-01 6.70738096e-02 6.76069042e-02 4.30753298e-02]
 [1.55889295e-02 1.46555410e-02 2.05909775e-03 5.88854107e-02]
 [1.16114970e-02 7.97313629e-03 3.64769133e-03 2.34241640e-02]
 [1.47526647e-03 3.61727402e-05 1.40607345e-02 1.49426609e-02]
 [1.16119970e-01 1.28518523e-02 1.54142983e-02 5.70822423e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.46196328e-04 3.00788130e-06 2.19039442e-05 9.72552105e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.97830594e-03 8.44007687e-02 1.08405497e-03 1.18890015e-01]
 [3.02797484e-02 2.64612449e-01 4.41389111e-03 1.55672954e-02]
 [1.20271253e-01 3.01498100e-03 9.66098718e-03 2.36024386e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.52463980e-03 1.24162585e-01 7.43106566e-01 2.62309375e-03]
 [2.61594610e-01 9.78972017e-01 2.11259429e-01 9.88536822e-02]
 [0.00000000e+00 0.00000000e+0

**Use our Q-table to play FrozenLake ! **👾

  After 10 000 episodes, our Q-table can be used as a "cheatsheet" to play FrozenLake"!
  
  By running this cell, you can see our agent playing FrozenLake:

In [0]:
env.reset()

state = env.reset()
step = 0
done = False
print("****************************************************")
print("STARTING ")
env.render()
for step in range(max_steps):

    # Take the action (index) that have the maximum expected future reward given that state
    action = np.argmax(qtable[state,:])

    new_state, reward, done, info = env.step(action)


    env.render()

    # We print the current step.
    print("Number of steps", step)
    if done:
      break
    state = new_state
env.close()

0
****************************************************
STARTING 

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 0
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 1
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 2
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 3
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 4
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 5
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 6
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 7
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 8
  (Right)
SFFF
FHFH
FFFH
HFFG
Number of steps 9
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 10
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 11
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 12
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 13
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 14
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 15
  (Left)
SFFF
FHFH
FFFH
HFFG
Number of steps 16
  (Up)
SFFF
FHFH
FFFH
HFFG
Number of steps 17
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 18
  (Up)
SFFF
FHFH
FFFH
HFFG


Let’s see how many times our agent finds the frisbee 🎉🎉🎉

To this end we will print the last step of the game.

In [0]:
env.reset()
games=5
state = env.reset()
step = 0
done = False
print("****************************************************")
print("STARTING ")
for game in range(games):
  for step in range(max_steps):

      # Take the action (index) that have the maximum expected future reward given that state
      action = np.argmax(qtable[state,:])

      new_state, reward, done, info = env.step(action)

      if done:
        # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
        env.render()

        # We print the number of step it took.
        print("Number of steps", step)
        done= False
        break
      state = new_state
  env.close()

****************************************************
STARTING 
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 92
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 0




---



---



# 🕹️CartPole 🕹️
That wasn't so hard 😎! How about trying to balance a pole so it does not fall? In this section we will address the [CartPole](https://gym.openai.com/envs/CartPole-v1/) problem, let's get to it!

![alt text](https://keon.io/images/deep-q-learning/animation.gif)



 As before we will use Q-learning to train our agent, so let's start by constructing our Q-table. We first need to find out the number of columns and rows of it. By checking the environment specifications of [OpenAi](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py), we see that the actions are left and right, so we need two columns for the actions. On the other hand, the state information is given by:

        Num	Observation                 Min         Max
        0	Cart Position             -4.8            4.8
        1	Cart Velocity             -Inf            Inf
        2	Pole Angle                 -24 deg        24 deg
        3	Pole Velocity At Tip      -Inf            Inf
      
   The cart position goes from -4.8 to 4.8 with a resolution of 0.01, that means $\frac{4.8 \times 2}{0.01}=960$ possible carts positions, while the cart velocity goes from $-\infty$ to $\infty$!!😵😵 Ohhhhh boi... How we are going to construct a table with $\infty$ rows[?!?!](https://www.youtube.com/watch?v=C3J1AO9z0tA&t=1m19s) 
   
 ![alt text](https://media1.giphy.com/media/HP0JqpBxLLGpO/giphy.gif?cid=3640f6095c71dd267138353159049ceb)
 
 
Do not panic! That is when deep learning steps up and takes over the stage 🎉🎉🎉. As you have already seen the use of deep Neural Networks as general function approximators have been proven to work very well in wide range of areas, reinforcement learning is not an exception. In this case we will use the NNs as function approximation between the mapping of states to actions, so for every input state, we want the NNs to output an approximation of the $Q\left(s,a\right)$.

![alt text](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn-images-1.medium.com%2Fmax%2F1318%2F1*Gh5PS4R_A5drl5ebd_gNrg%402x.png&f=1)

In this particular scenario, the input layer will have the same number of inputs as environment parameters, 4, and the output layer will have the same number of outputs as actions, in this case 2. 

**Reward:** A reward of +1 is provided for every timestep that the pole remains upright. The episode ends when the pole is more than 15 degrees from vertical.



**Step 0: Import the needed libraries**

We start by importing the needed libraries:
We will be using 3 libraries:
* Keras: for our DNNs.
* OpenAI Gym: for our CartPole Environment
* Random: to generate random numbers.
* Collections: Collection will be use to create a memory buffer to store the tuples $\left(S_t, A_t, R_t,S_{t+1}\right)$ of transactions. 

The idea behind the use of a memory buffer is that most optimization algorithms, including gradient descent, assume that the samples which the gradient is obtained are independent and identically distributed. Clearly in the defined environment is not the case, however, by sampling uniformly the memory buffer with a high number of samples the correlation between contiguous samples is broken and less likely to be correlated samples are used to update the networks weights, leading to a stable optimization of the action-parameter selection.


In [0]:

import random
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import os

Using TensorFlow backend.


**The Agent**

Let's start by coding a general DQ-Learning agent. The state and action size are passed as parameters and we configure a replay buffer to have capacity to store 2000 experienced transitions.

In [0]:
 class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()

Now we address the DDNs; we are going to use two fully connected layers of 24 neurons each and as an optimizer we select  adam optimizer.

In [0]:
    def _build_model(self):
            # Neural Net for Deep-Q learning Model
            model = Sequential()
            model.add(Dense(24, input_dim=self.state_size, activation='relu'))
            model.add(Dense(24, activation='relu'))
            model.add(Dense(self.action_size, activation='linear'))
            model.compile(loss='mse',
                          optimizer=Adam(lr=self.learning_rate))
            return model

Now define the method to store the transictions into the memory buffer.
The parameter done is a boolean returned true when the pole has fallen. 

In [0]:
    def remember(self, state, action, reward, next_state, done):
          self.memory.append((state, action, reward, next_state, done))

Again, we implement and $\epsilon-greedy$ policy.

In [0]:
     def act(self, state):
            if np.random.rand() <= self.epsilon:
                return random.randrange(self.action_size)
            act_values = self.model.predict(state)
            return np.argmax(act_values[0]) # returns action

Then comes the implementation of the Q-Learning method:



1.   We obtain the samples to train the DNN from the replay buffer.
2.  We compute $target=r+\gamma \max _{a} Q\left(s_{t+1},a\right)$, by doing a forward pass using next_state value.
3. We do a forward pass through the network to obtain the $Q\left(s,a\right)$ for all the possible actions.
4. In order to just update the paramater of the action taken, we copy target to the value of the $Q\left(s,a\right)$ of the actual $a$ taken.
5. We update the parameters of the network using MSE as loss function.




In [0]:
    def replay(self, batch_size):
            minibatch = random.sample(self.memory, batch_size)
            for state, action, reward, next_state, done in minibatch:
                target = reward
                if not done:
                    target = (reward + self.gamma *
                              np.amax(self.model.predict(next_state)[0]))
                target_f = self.model.predict(state)
                target_f[0][action] = target
                self.model.fit(state, target_f, epochs=1, verbose=0)
            if self.epsilon > self.epsilon_min:
                self.epsilon *= self.epsilon_decay


Now we define the operations to load and save the models.

In [0]:
def load(self, name):
        self.model.load_weights(name)
def save(self, name):
        self.model.save_weights(name)

Code Lab might not recognize all the previous code parts defined under the same class, to this end we run everything this time altogether. 

In [0]:
class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95    # discount rate
        self.epsilon = 1.0  # exploration rate
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.001
        self.model = self._build_model()

    def _build_model(self):
        # Neural Net for Deep-Q learning Model
        model = Sequential()
        model.add(Dense(24, input_dim=self.state_size, activation='relu'))
        model.add(Dense(24, activation='relu'))
        model.add(Dense(self.action_size, activation='linear'))
        model.compile(loss='mse',
                      optimizer=Adam(lr=self.learning_rate))
        return model

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):# We implement the epsilon-greedy policy
        if np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state)
        return np.argmax(act_values[0]) # returns action
      
    def exploit(self, state): # When we test the agent we dont want it to explore anymore, but to exploit what it has learnt
        act_values = self.model.predict(state)
        return np.argmax(act_values[0]) 

    def replay(self, batch_size):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            if not done:
                target = (reward + self.gamma *
                          np.amax(self.model.predict(next_state)[0]))
            target_f = self.model.predict(state)
            target_f[0][action] = target
            self.model.fit(state, target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay
    def load(self, name):
        self.model.load_weights(name)
    def save(self, name):
        self.model.save_weights(name)

**Main**

Following we implement the training of the agent. (Warning: it might take a while)

In [0]:
if __name__ == "__main__":
    EPISODES = 500
    env = gym.make('CartPole-v1')
    state_size = env.observation_space.shape[0]
    action_size = env.action_space.n
    agent = DQNAgent(state_size, action_size)
    done = False
    batch_size = 32

    for e in range(EPISODES):
        state = env.reset()
        state = np.reshape(state, [1, state_size])
        for time in range(500):
            action = agent.act(state)
            next_state, reward, done, _ = env.step(action)
            reward = reward if not done else -10
            next_state = np.reshape(next_state, [1, state_size])
            agent.remember(state, action, reward, next_state, done)
            state = next_state
            if done:
                print("episode: {}/{}, score: {}, e: {:.2}"
                      .format(e, EPISODES, time, agent.epsilon))
                break
            if len(agent.memory) > batch_size:
                agent.replay(batch_size)

Instructions for updating:
Colocations handled automatically by placer.
episode: 0/500, score: 12, e: 1.0
episode: 1/500, score: 13, e: 1.0
Instructions for updating:
Use tf.cast instead.
episode: 2/500, score: 21, e: 0.92
episode: 3/500, score: 30, e: 0.79
episode: 4/500, score: 17, e: 0.73
episode: 5/500, score: 11, e: 0.69
episode: 6/500, score: 22, e: 0.62
episode: 7/500, score: 9, e: 0.59
episode: 8/500, score: 9, e: 0.56
episode: 9/500, score: 9, e: 0.54
episode: 10/500, score: 12, e: 0.51
episode: 11/500, score: 11, e: 0.48
episode: 12/500, score: 18, e: 0.44
episode: 13/500, score: 65, e: 0.32
episode: 14/500, score: 50, e: 0.25
episode: 15/500, score: 59, e: 0.18
episode: 16/500, score: 47, e: 0.15
episode: 17/500, score: 76, e: 0.099
episode: 18/500, score: 64, e: 0.072
episode: 19/500, score: 74, e: 0.05
episode: 20/500, score: 108, e: 0.029
episode: 21/500, score: 94, e: 0.018
episode: 22/500, score: 125, e: 0.01
episode: 23/500, score: 76, e: 0.01
episode: 24/500, score: 6

Let's now visualize how the agent is performing:

In [0]:
!apt-get install -y xvfb python-opengl > /dev/null 2>&1
!pip install gym pyvirtualdisplay > /dev/null 2>&1

In [0]:
import gym
import numpy as np
import matplotlib.pyplot as plt
from IPython import display as ipythondisplay
from pyvirtualdisplay import Display
display = Display(visible=0, size=(400, 300))
display.start()
from gym.wrappers import Monitor
import glob
import io
import base64

In [0]:
"""
Utility functions to enable video recording of gym environment and displaying it
To enable video, just do "env = wrap_env(env)""
"""

def show_video():
  mp4list = glob.glob('video/*.mp4')
  if len(mp4list) > 0:
    mp4 = mp4list[0]
    video = io.open(mp4, 'r+b').read()
    encoded = base64.b64encode(video)
    ipythondisplay.display(HTML(data='''<video alt="test" autoplay 
                loop controls style="height: 400px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
  else: 
    print("Could not find video")
    

def wrap_env(env):
  env = Monitor(env, './video', force=True)
  return env

In [0]:
env = wrap_env(gym.make('CartPole-v1'))
state_size = env.observation_space.shape[0]
action_size = env.action_space.n
done = False
state = env.reset()
state = np.reshape(state, [1, state_size])
for time in range(500):
    screen = env.render()
    action = agent.exploit(state)
    state, reward, done, _ = env.step(action)
    state = np.reshape(state, [1, state_size])

    if done:
        print("episode: {}/{}, score: {}, e: {:.2}"
              .format(e, EPISODES, time, agent.epsilon))
        break
env.close()
show_video()
env.reset()



---

# Don't stop me now 🙈!!
![alt text](https://media0.giphy.com/media/GIIC4jmmUlXZS/giphy.gif?cid=3640f6095c71dc3e396a754159b0c5af)

If you are thirsty for more, why not trying new environments of OpenAI such as[ mountain car ](https://gym.openai.com/envs/MountainCarContinuous-v0/) using the same RL as Q-learning or, to reduce variance and increase performance implement a [double Q-Learning](https://arxiv.org/pdf/1509.06461.pdf)?

If you really fancy DRL, have a look of the tutorials and code prepared by [OpenAI](https://spinningup.openai.com/en/latest/user/introduction.html).